### ISSUE TITLE
Analise do HTML feito em sala de aula.

### ISSUE THREAD

**Issue by MOVelasco** [murtam99/EstudoSalaDeAula#1]
Olá Matheus.
Estou olhando primeiro arquivo que fizemos na nossa primeira aula de HTML, e o seu documento html, não está bem formatado e endentado, já que fizemos ele em Notepad++. Com a intenção de aprendermos a utilidade de um código endentado.
Algumas observações:  na linha 2 de seu documento **HTML** vocês esta com a **TAG** ``<html> lang="pt-br">`` por esse motivo está **aparecendo na página: ``lang="pt-br">``.**
Na linha 9, dentro do escopo do ``<style>`` o seletor é **h1** e você colocou ``<h1``, por esse motivo não esta funcionando.
**OBS:** Colocando o estilo do h1 separado na área de estilo, não precisa da formatação em linha, digo na TAG h1. OK?
Me da um retorno.

**Comment by murtam99** [comment]
Professor, já fiz as mudanças que você comentou. Obrigado!
